library:
  BOOK_STOCK: "/books"
  NEW_ACQUISITIONS: "/books/new"
  TRASH: "/books/trash"
  POLL_PERIOD: 60

language:
  DEFAULT: "ru"

database:
  DSN: "flibgo:flibgo@tcp(db:3306)/flibgo?charset=utf8"
  INIT_SCRIPT: "config/mysql_db_init.sql"
  DROP_SCRIPT: "config/mysql_db_drop.sql"
  MAX_SCAN_THREADS: 3

genres:
  TREE_FILE: "config/genres.xml"
  # TREE_FILE: "config/alt_genres.xml"
  
logs:
  OPDS: "logs/opds.log"
  SCAN: "logs/scan.log"
  DEBUG: false

opds:
  PORT: 8085
  PAGE_SIZE: 30

